nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:8080', 'http://127.0.0.1:8080', 'http://localhost:8001', 'http://127.0.0.1:8001']
    allow_headers: ['Content-Type', 'Accept', 'Authorization']
    expose_headers: ['Link', 'Content-Type']
    allow_methods: ['GET', 'POST', 'OPTIONS', 'DELETE']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000', 'http://127.0.0.1:3000', 'http://localhost:5173', 'http://127.0.0.1:5173', 'http://localhost:8080', 'http://127.0.0.1:8080', 'http://localhost:8001', 'http://127.0.0.1:8001']
      allow_credentials: true
      allow_headers: ['Content-Type', 'Accept', 'Authorization']
      expose_headers: ['Link', 'Content-Type']
      allow_methods: ['GET', 'POST', 'OPTIONS', 'DELETE']
      max_age: 3600
