nelmio_cors:
  paths:
    '^/api/':
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_credentials: true
      allow_headers: ['Content-Type', 'Accept', 'Authorization']
      expose_headers: ['Link', 'Content-Type']
      allow_methods: ['GET', 'POST', 'OPTIONS', 'DELETE']
      max_age: 3600
